### ISSUE TITLE
Documentation around filtered streams

### ISSUE THREAD

**Issue by mfreeman612** [michimani/gotwi#258]
Yoshihiro-san, thank you for your hard work and this great library. I am wondering if it would be possible for you to add documentation to maybe include some examples or explanations around listening for incoming tweet streams.

thanks

**Comment by michimani** [comment]
@mfreeman612 

Thanks for your input!

I will add a sample of "filtered streams" in the example implementation.

**Comment by mfreeman612** [comment]
Any idea on how to keep a filteredStream from closing? I can read tweets for a while and then it closes

**Comment by mfreeman612** [comment]
awesome, thank you!

**Comment by mfreeman612** [comment]
For others who might be reading this, this seems to be working:

```
&gotwi.NewClientInput{
		AuthenticationMethod: gotwi.AuthenMethodOAuth2BearerToken,
		HTTPClient:           &http.Client{Timeout: 0},
	}
```

**Comment by michimani** [comment]
Thank you for your patience.
I have added an example implementation using the `filteredstream` package, so please check it out.
