### ISSUE TITLE
author_id returns blank

### ISSUE THREAD

**Issue by toul-codes** [michimani/gotwi#291]
Hi @michimani  excellent library, 

I did encounter, what I think is a bug. 

Whenever following the `filteredstreams` example I noticed that the `t.Data.AuthorID` is always **blank** on the returned output.

This was very tricky to track down for me lol.

I think maybe the endpoint is **not** being generated correctly if it is being done so dynamically.

For example when I [hardcoded the endpoint](https://github.com/michimani/gotwi/blob/faead303122de77e9108116f7818312a5a41d4cd/tweet/filteredstream/api.go#L13) to be the following; 

`searchStreamEndpoint = "https://api.twitter.com/2/tweets/search/stream?tweet.fields=author_id,id,text"`

I was able to retrieve the `author_id`

Not, sure how to remedy it in the code but will try to do so...

**Comment by cgrinds** [comment]
hi @toul-codes if you're using the `filtered_stream` example you'll need to change this line https://github.com/michimani/gotwi/blob/faead303122de77e9108116f7818312a5a41d4cd/_examples/4_filtered_stream/filtered_stream.go#L92

to something like this, which tells Twitter to return the author id in the response.

```go
p := &types.SearchStreamInput{
	TweetFields: fields.TweetFieldList{
		fields.TweetFieldAuthorID,
	},
}
```

**Comment by michimani** [comment]
Hi @toul-codes, thanks for asking this question.

As @cgrinds already commented, could you try to fix the `SearchStreamInput`?  

Twitter API v2 requires some fields to be explicitly specified in order to be included in the response, and this `author_id` is one of them.

Thanks for your prompt advice! > @cgrinds

**Comment by toul-codes** [comment]
Hi thank you @cgrinds  and @michimani  for the quick response. The proposed code worked!
